// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ_qk4J3eUDamPaJy6Km7uA4s5iW4OjkY',
    appId: '1:482813515235:web:1e2311c49d6fbc518d3cd6',
    messagingSenderId: '482813515235',
    projectId: 'insurance-company-test',
    authDomain: 'insurance-company-test.firebaseapp.com',
    storageBucket: 'insurance-company-test.firebasestorage.app',
    measurementId: 'G-04EQP3L5CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW65f2Ta6py_21OgHokyjaO0qpz8kMlJo',
    appId: '1:482813515235:android:122c43359c5c92b18d3cd6',
    messagingSenderId: '482813515235',
    projectId: 'insurance-company-test',
    storageBucket: 'insurance-company-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1pc_IG8PJxbeiRD0bfVsJzogSB8bs3gM',
    appId: '1:482813515235:ios:46ba022f99cd17c28d3cd6',
    messagingSenderId: '482813515235',
    projectId: 'insurance-company-test',
    storageBucket: 'insurance-company-test.firebasestorage.app',
    iosBundleId: 'com.example.insuranceCompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1pc_IG8PJxbeiRD0bfVsJzogSB8bs3gM',
    appId: '1:482813515235:ios:46ba022f99cd17c28d3cd6',
    messagingSenderId: '482813515235',
    projectId: 'insurance-company-test',
    storageBucket: 'insurance-company-test.firebasestorage.app',
    iosBundleId: 'com.example.insuranceCompany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ_qk4J3eUDamPaJy6Km7uA4s5iW4OjkY',
    appId: '1:482813515235:web:ee627779c4c2d6188d3cd6',
    messagingSenderId: '482813515235',
    projectId: 'insurance-company-test',
    authDomain: 'insurance-company-test.firebaseapp.com',
    storageBucket: 'insurance-company-test.firebasestorage.app',
    measurementId: 'G-ZLFK77VJE6',
  );
}
